In [3]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import tensorflow as tf

1.Create a vector,scalar,matrix, and tensor with values of your choice using tf.constant()

In [5]:
scalar = tf.constant(7)
print("Scalar:", scalar)
vector = tf.constant([1, 2, 3])
print("Vector:", vector)
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)
tensor = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("Tensor:", tensor)


Scalar: tf.Tensor(7, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


2.Find the shape,rank and size of the tensor 

In [6]:
shape = tensor.shape
rank = tf.rank(tensor).numpy()  
size = tf.size(tensor).numpy()  

print("Shape of tensor:", shape)
print("Rank of tensor:", rank)
print("Size of tensor:", size)

Shape of tensor: (2, 2, 2)
Rank of tensor: 3
Size of tensor: 8


3.create  two tensors contaibning random values between 0 and 1

In [7]:
tensor_a = tf.random.uniform((5, 300), minval=0, maxval=1, dtype=tf.float32)
tensor_b = tf.random.uniform((5, 300), minval=0, maxval=1, dtype=tf.float32)
print("Tensor 1:", tensor_a)
print("Tensor 2:", tensor_b)

Tensor 1: tf.Tensor(
[[5.3000212e-02 5.8544660e-01 5.3159177e-01 ... 5.1510334e-04
  9.9385977e-02 1.6521311e-01]
 [1.0655892e-01 7.6928747e-01 3.5286391e-01 ... 4.3424571e-01
  7.2878861e-01 1.9706655e-01]
 [2.7094877e-01 5.9896731e-01 3.2038152e-01 ... 2.4958789e-01
  5.4024696e-02 1.9765258e-01]
 [1.6970515e-01 9.8061180e-01 9.5569682e-01 ... 6.2592149e-01
  1.4336801e-01 6.8273425e-02]
 [4.8703492e-01 3.6633110e-01 3.4883344e-01 ... 9.4833004e-01
  9.1235375e-01 3.2963800e-01]], shape=(5, 300), dtype=float32)
Tensor 2: tf.Tensor(
[[0.6958941  0.97483337 0.98602605 ... 0.8487148  0.0848521  0.38772297]
 [0.08486784 0.25289774 0.5215285  ... 0.72845733 0.01117563 0.9871025 ]
 [0.49232078 0.45286942 0.9640913  ... 0.58492494 0.38056266 0.61086464]
 [0.11769605 0.25116193 0.9101765  ... 0.65082216 0.5378654  0.30962908]
 [0.941239   0.87817216 0.5094656  ... 0.05957818 0.7978648  0.9987472 ]], shape=(5, 300), dtype=float32)


4.Multiply the two tensors using matrix multiplication

In [8]:
result_matrix_multiplication = tf.matmul(tensor_a, tensor_b, transpose_b=True)
print("Matrix Mul:")
print(result_matrix_multiplication)


Matrix Mul:
tf.Tensor(
[[76.34744  74.601425 74.3701   74.5726   75.33116 ]
 [79.49814  78.37714  77.430984 75.70791  78.4225  ]
 [78.34624  76.66594  72.158806 74.23645  73.73345 ]
 [75.96513  74.87295  76.28128  73.13519  74.257965]
 [77.13017  75.62932  74.6942   75.81073  72.212006]], shape=(5, 5), dtype=float32)


5.Multipy the two tensors using dot product

In [10]:
result_dot_product = tf.reduce_sum(tf.multiply(tensor_a, tensor_b), axis=1)
print("Matrix Multiplication Result Shape:", result_matrix_multiplication.shape)
print("Dot Product Result:", result_dot_product)

Matrix Multiplication Result Shape: (5, 5)
Dot Product Result: tf.Tensor([76.34745  78.37713  72.158806 73.1352   72.21201 ], shape=(5,), dtype=float32)


Create a tensor with random values between 0 and 1 with shape [224,224,3]

In [16]:
random_tensor = tf.random.uniform([224, 224, 3], minval=0, maxval=1, dtype=tf.float32)
print("Random tensor:")
print(random_tensor)

Random tensor:
tf.Tensor(
[[[0.5968492  0.01508689 0.44445503]
  [0.9739535  0.5637455  0.33995473]
  [0.73984456 0.41404307 0.9158573 ]
  ...
  [0.57380795 0.39030337 0.43301892]
  [0.29906273 0.12536502 0.907575  ]
  [0.88520706 0.12134576 0.72304416]]

 [[0.18428218 0.78424776 0.813967  ]
  [0.9637066  0.38206077 0.83242524]
  [0.80342853 0.24510765 0.10894692]
  ...
  [0.8565502  0.91981804 0.23207664]
  [0.11873019 0.7200178  0.57989335]
  [0.15274107 0.35841978 0.08689654]]

 [[0.11955893 0.98009133 0.42567062]
  [0.7521633  0.52666986 0.7897953 ]
  [0.77240515 0.7374661  0.96494937]
  ...
  [0.68090487 0.03227317 0.8689269 ]
  [0.63291657 0.907596   0.04608107]
  [0.33027554 0.66045845 0.33965492]]

 ...

 [[0.12440848 0.01556516 0.47028208]
  [0.27419674 0.8925979  0.8211752 ]
  [0.15623724 0.10124159 0.38014472]
  ...
  [0.85415876 0.36432338 0.84993315]
  [0.31461358 0.68668556 0.9537158 ]
  [0.11652279 0.12533963 0.45865262]]

 [[0.61932206 0.92234206 0.02011538]
  [0.983405

7. Find the min and max values of the tensor

In [12]:
min_value = tf.reduce_min(random_tensor)
max_value = tf.reduce_max(random_tensor)
print("Min value of tensor:", min_value.numpy())
print("Max value of tensor:", max_value.numpy())

Min value of tensor: 8.34465e-07
Max value of tensor: 0.9999801


8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [13]:
random_tensor_4d = tf.random.uniform([1, 224, 224, 3], minval=0, maxval=1, dtype=tf.float32)
squeezed_tensor = tf.squeeze(random_tensor_4d)
print("Shape of tensor after squeezing:", squeezed_tensor.shape)

Shape of tensor after squeezing: (224, 224, 3)


9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [14]:
my_tensor = tf.constant([1.0, 5.0, 3.0, 9.0, 7.0, 6.0, 2.0, 8.0, 4.0, 0.0])
max_index = tf.argmax(my_tensor)
print("Index of max value:", max_index.numpy())

Index of max value: 3


10. One-hot encode the tensor you have created in 9

In [15]:
one_hot_encoded = tf.one_hot(max_index, depth=10)
print("One-hot encoded tensor:", one_hot_encoded.numpy())

One-hot encoded tensor: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
